name: 'CapRover Docker Deploy'
description: 'Action to deploy deocker image on Caprover server'
author: 'Sai Kiran Anagani'
branding:
  icon: upload-cloud
  color: red
inputs:
  server:
    description: 'CapRover admin panel URL. Ex. https://captain.root.domain.com'
    required: true
  password:
    description: 'CapRover admin password. Use $\{{ secrets.CAPROVER_PASSWORD }} for better security.'
    required: true
  appname:
    description: 'Application name on the CapRover server. Must exists.'
    required: true
  docker:
    description: 'Docker image which must be deployed'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
